#!/usr/bin/env bash
# =============================================================================
#  PortGuard agent installer — turns a fresh Ubuntu server into a managed node.
#
#  Run ON THE NEW SERVER (generated by the master's Servers page):
#    sudo bash portguard-agent-install.sh -master http://MASTER:8080 -token TOKEN
#
#  What it does:
#    1. downloads the master's own portguard binary (same version, no Go build)
#    2. installs it as /opt/portguard-agent/portguard
#    3. creates the systemd unit running it in agent mode (headless node)
#    4. registers the node role (generic/iran/foreign)
#    5. opens the agent port in ufw when active
#
#  The node never runs a panel; the master manages everything remotely.
# =============================================================================
set -euo pipefail

APP_DIR="/opt/portguard-agent"
UNIT="/etc/systemd/system/portguard-agent.service"
AGENT_PORT="${AGENT_PORT:-8081}"
MASTER=""
TOKEN=""
NAME=""
HOSTIP=""
ROLE="${ROLE:-generic}"

say() { echo -e "\033[1;35m[agent-install]\033[0m $*"; }
die() { echo -e "\033[1;31m[agent-install:ERROR]\033[0m $*" >&2; exit 1; }

[ "$(id -u)" = "0" ] || die "run as root (sudo)"

# ---- parse args ----
while [ $# -gt 0 ]; do
  case "$1" in
    -master) MASTER="$2"; shift 2 ;;
    -token)  TOKEN="$2"; shift 2 ;;
    -role)   ROLE="$2"; shift 2 ;;
    -name)   NAME="$2"; shift 2 ;;
    -host)   HOSTIP="$2"; shift 2 ;;
    -port)   AGENT_PORT="$2"; shift 2 ;;
    *) die "unknown option: $1" ;;
  esac
done
[ -n "$MASTER" ] || die "usage: bash portguard-agent-install.sh -master http://MASTER:8080 -token TOKEN [-role generic] [-port 8081]"
[ -n "$TOKEN" ]  || die "missing -token"
case "$ROLE" in generic|iran|foreign) ;; *) die "role must be generic, iran or foreign" ;; esac

# ---- prerequisites ----
command -v curl >/dev/null 2>&1 || {
  export DEBIAN_FRONTEND=noninteractive
  apt-get update -y -qq >/dev/null 2>&1
  apt-get install -y -qq curl >/dev/null 2>&1
}

# ---- download the master's binary (same version by construction) ----
say "downloading portguard binary from the master (${MASTER})…"
mkdir -p "$APP_DIR"
if ! curl -fsSL --connect-timeout 10 "${MASTER}/api/node/binary" -o "${APP_DIR}/portguard.new"; then
  die "could not download the binary — is the master reachable and the token valid on ${MASTER}?"
fi
chmod +x "${APP_DIR}/portguard.new"

# smoke-test the binary in agent mode before touching anything else
if ! "${APP_DIR}/portguard.new" agent -help >/dev/null 2>&1 && ! "${APP_DIR}/portguard.new" -help >/dev/null 2>&1; then
  # -help exits non-zero on flag packages; try the version print instead
  # pipefail + SIGPIPE: `head -1` closes the pipe and the binary exits 141,
  # which would fail the pipeline even on a match - capture the line first
  SMOKE="$("${APP_DIR}/portguard.new" 2>&1 | head -1 || true)"
  echo "$SMOKE" | grep -qi portguard     || die "downloaded binary failed its smoke test — the master may serve a different arch"

fi

mv "${APP_DIR}/portguard.new" "${APP_DIR}/portguard"

# ---- data dir + systemd ----
mkdir -p /var/lib/portguard
cat > "$UNIT" <<EOF
[Unit]
Description=PortGuard managed node (agent)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=${APP_DIR}/portguard agent -port ${AGENT_PORT} -token ${TOKEN} -role ${ROLE}
Restart=always
RestartSec=3
LimitNOFILE=1000000

[Install]
WantedBy=multi-user.target
EOF
systemctl daemon-reload
systemctl enable --now portguard-agent

# ---- firewall ----
if command -v ufw >/dev/null 2>&1 && ufw status 2>/dev/null | grep -qi "Status: active"; then
  ufw allow "${AGENT_PORT}/tcp" >/dev/null 2>&1 && say "ufw: allowed ${AGENT_PORT}/tcp"
fi

sleep 1
systemctl is-active --quiet portguard-agent \
  && say "agent running on port ${AGENT_PORT} (role: ${ROLE}) — add this server in the master's Servers page now:" \
  && say "   host: <this-server-ip>   port: ${AGENT_PORT}   token: (the one you used)" \
  || { journalctl -u portguard-agent -n 20 --no-pager; die "agent failed to start"; }

# ---- self-register: announce this server to the master ----
REG_NAME="${NAME:-$(hostname)}"
REG_HOST="${HOSTIP:-$(curl -fsSL -m 8 "${MASTER}/api/node/myip" 2>/dev/null || true)}"
REG_NAME=${REG_NAME//\"/}
if [ -n "$REG_HOST" ]; then
  if curl -fsSL -m 10 -X POST -H "Authorization: Bearer ${TOKEN}" -H 'Content-Type: application/json' -d "{\"name\":\"${REG_NAME}\",\"host\":\"${REG_HOST}\",\"port\":${AGENT_PORT},\"role\":\"${ROLE}\"}" "${MASTER}/api/nodes/self-register" >/dev/null 2>&1; then
    say "registered with the master (${REG_HOST}:${AGENT_PORT}) - manage it from the Servers page"
  else
    say "WARNING: self-register failed - add the node manually in the master's Servers page"
  fi
else
  say "WARNING: could not determine this server's address - add the node manually in the master's Servers page"
fi
