package proxy

import (
	"fmt"
	"os"
	"regexp"
	"os/exec"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"portguard/internal/store"
)

// HAProxyEngine owns /etc/haproxy/haproxy.cfg. UDP is not supported by HAProxy.
type HAProxyEngine struct{}

func (HAProxyEngine) Name() string { return "haproxy" }

func (HAProxyEngine) ActiveFiles(p Paths) []string {
	return []string{p.HAProxyConf}
}

func (HAProxyEngine) LivePath(p Paths, rel string) string {
	return p.HAProxyConf
}

func (HAProxyEngine) StagedRel(p Paths, live string) (string, bool) {
	if live == p.HAProxyConf {
		return "haproxy.cfg", true
	}
	return "", false
}

func (HAProxyEngine) Render(mappings []store.Mapping, certs map[int64]store.Cert, p Paths) (map[string]string, error) {
	sorted := make([]store.Mapping, len(mappings))
	copy(sorted, mappings)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].ID < sorted[j].ID })

	var b strings.Builder
	b.WriteString(`# Generated by PortGuard — do not edit manually.
global
    log /dev/log local0
    log /dev/log local1 notice
    maxconn 4096
    user haproxy
    group haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    ca-base /etc/ssl/certs
    crt-base /etc/ssl/private

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5s
    timeout client  30s
    timeout server  30s
    option  forwardfor
    retries 2

`)

	for _, m := range sorted {
		if !m.Enabled || m.Engine != "haproxy" {
			continue
		}
		tag := fmt.Sprintf("pg%d", m.ID)
		fe := "fe_" + tag
		be := "be_" + tag
		bind := fmt.Sprintf("bind %s:%d", bindIP(m.ListenIP), m.ListenPort)

		switch m.Protocol {
		case "http":
			// each mapping owns its own bind port (conflicts are rejected upstream),
			// so no host-based routing is needed here.
			fmt.Fprintf(&b, "frontend %s\n    %s\n", fe, bind)
			b.WriteString(renderHAAccessRules(m, false))
			if m.RedirectTo != "" {
				fmt.Fprintf(&b, "    http-request redirect location %s code 301\n", escapeHA(m.RedirectTo))
			} else {
				b.WriteString(renderHARouteRules(fe, be, m))
				b.WriteString(renderHAPathRoutes(fe, be, m))
				b.WriteString(renderHAPathACL(fe, be, m))
				fmt.Fprintf(&b, "    default_backend %s\n", be)
			}
			b.WriteString(renderHARouteRuleBackends(m))
			if m.WebSocket {
				fmt.Fprintf(&b, "    timeout tunnel 3600s\n")
			}
			b.WriteString(renderHABackend(be, m, false))
		case "https":
			if m.SSLCertID == nil {
				return nil, fmt.Errorf("mapping #%d: https requires a certificate", m.ID)
			}
			pem := posixJoin(p.CertsDir, fmt.Sprintf("%d.pem", *m.SSLCertID))
			alpn := ""
			if m.HTTP2 {
				alpn = " alpn h2,http/1.1"
			}
			fmt.Fprintf(&b, "frontend %s\n    %s ssl crt %s%s\n", fe, bind, escapeHA(pem), alpn)
			b.WriteString(renderHAAccessRules(m, false))
			if m.RedirectTo != "" {
				fmt.Fprintf(&b, "    http-request redirect location %s code 301\n", escapeHA(m.RedirectTo))
			} else {
				b.WriteString(renderHARouteRules(fe, be, m))
				b.WriteString(renderHAPathRoutes(fe, be, m))
				b.WriteString(renderHAPathACL(fe, be, m))
				fmt.Fprintf(&b, "    default_backend %s\n", be)
			}
			b.WriteString(renderHARouteRuleBackends(m))
			if m.WebSocket {
				fmt.Fprintf(&b, "    timeout tunnel 3600s\n")
			}
			b.WriteString(renderHABackend(be, m, false))
		case "tcp":
			fmt.Fprintf(&b, "frontend %s\n    mode tcp\n    option tcplog\n    %s\n", fe, bind)
			b.WriteString(renderHAAccessRules(m, true))
			fmt.Fprintf(&b, "    default_backend %s\n", be)
			b.WriteString(renderHABackend(be, m, true))
		case "udp":
			return nil, fmt.Errorf("mapping #%d: HAProxy does not support UDP forwarding", m.ID)
		}
	}

	appendDynBackends(&b, sorted)
	b.WriteString("\n# --- end of PortGuard mappings ---\n")
	return map[string]string{"haproxy.cfg": b.String()}, nil
}

// appendDynBackends writes the dynamic backends after the main mapping loop.
func appendDynBackends(b *strings.Builder, sorted []store.Mapping) {
	for _, m := range sorted {
		if !m.Enabled || m.Engine != "haproxy" || len(m.PathRoutes) == 0 || m.RedirectTo != "" {
			continue
		}
		if m.Protocol != "http" && m.Protocol != "https" {
			continue
		}
		b.WriteString(renderHADynBackend(fmt.Sprintf("be_pg%d", m.ID), m))
	}
}

func renderHABackend(be string, m store.Mapping, tcpMode bool) string {
	var b strings.Builder
	balance := m.Balance
	if balance == "" {
		balance = "roundrobin"
	}
	if tcpMode {
		fmt.Fprintf(&b, "backend %s\n    mode tcp\n    balance %s\n", be, balance)
	} else {
		fmt.Fprintf(&b, "backend %s\n    balance %s\n", be, balance)
		if m.HostHeader != "" {
			fmt.Fprintf(&b, "    http-request set-header Host %s\n", escapeHA(m.HostHeader))
		}
	}
	for i, t := range m.Targets {
		fmt.Fprintf(&b, "%s\n", backendLine(fmt.Sprintf("s%d", i), t, true))
	}
	if m.WebSocket {
		b.WriteString("    timeout tunnel 3600s\n")
	}
	b.WriteString("\n")
	return b.String()
}

// renderHARouteRules emits ordered path_beg ACLs + use_backend lines for the
// advanced routing rules. HAProxy evaluates ACLs in file order, so rule
// order is preserved as-is (with longest prefixes first for sanity).
func renderHARouteRules(fe, be string, m store.Mapping) string {
	if len(m.Routes) == 0 {
		return ""
	}
	type active struct {
		id   int64
		path string
	}
	var rules []active
	for _, r := range m.Routes {
		if r.Enabled {
			rules = append(rules, active{id: r.ID, path: r.Path})
		}
	}
	// longest prefix first so specific rules win over generic ones
	for i := 1; i < len(rules); i++ {
		for j := i; j > 0 && len(rules[j].path) > len(rules[j-1].path); j-- {
			rules[j], rules[j-1] = rules[j-1], rules[j]
		}
	}
	var b strings.Builder
	for _, r := range rules {
		aclName := fmt.Sprintf("%s_r%d", fe, r.id%100000)
		fmt.Fprintf(&b, "    acl %s path_beg %s\n", aclName, escapeHA(r.path))
		if ruleHasRedirect(m, r.id) {
			url := ruleRedirect(m, r.id)
			fmt.Fprintf(&b, "    http-request redirect location %s code 301 if %s\n", escapeHA(url), aclName)
		} else {
			fmt.Fprintf(&b, "    use_backend %s_r%d if %s\n", be, r.id%100000, aclName)
		}
	}
	return b.String()
}

// renderHARouteRuleBackends emits one backend per multi-target rule; single
// targets get an inline backend too (uniform and diff-friendly).
func renderHARouteRuleBackends(m store.Mapping) string {
	if len(m.Routes) == 0 {
		return ""
	}
	var b strings.Builder
	for _, r := range m.Routes {
		if !r.Enabled || len(r.Targets) == 0 {
			continue
		}
		rb := store.Mapping{
			Engine: m.Engine, Protocol: "http", Targets: r.Targets,
			Balance: m.Balance, WebSocket: m.WebSocket, HostHeader: m.HostHeader,
		}
		out := renderHABackend(fmt.Sprintf("be_pg%d_r%d", m.ID, r.ID%100000), rb, false)
		b.WriteString(strings.TrimRight(out, "\n") + "\n\n")
	}
	return b.String()
}

func ruleHasRedirect(m store.Mapping, id int64) bool {
	for _, r := range m.Routes {
		if r.ID == id && r.Redirect != "" {
			return true
		}
	}
	return false
}

func ruleRedirect(m store.Mapping, id int64) string {
	for _, r := range m.Routes {
		if r.ID == id {
			return r.Redirect
		}
	}
	return ""
}

// renderHAPathACL adds path-based routing (like haproxy-manager's ACL path rules):
// traffic matching the prefix goes to the backend, everything else gets a 404.
func renderHAPathACL(fe, be string, m store.Mapping) string {
	if m.PathPrefix == "" {
		return ""
	}
	var b strings.Builder
	fmt.Fprintf(&b, "    acl %s_path path_beg %s\n", fe, escapeHA(m.PathPrefix))
	fmt.Fprintf(&b, "    use_backend %s if %s_path\n", be, fe)
	fmt.Fprintf(&b, "    http-request deny deny_status 404 if !%s_path\n", fe)
	return b.String()
}

// renderHAPathRoutes emits the frontend rules for dynamic port-in-path
// transports (/<prefix>/<port>): one ACL per route plus Upgrade-header
// enforcement for ws/httpupgrade. Traffic matching any route goes to the
// mapping's dynamic backend where the port is extracted per request.
func renderHAPathRoutes(fe, be string, m store.Mapping) string {
	if len(m.PathRoutes) == 0 {
		return ""
	}
	var b strings.Builder
	var aclNames []string
	needUpgrade := false
	for _, pr := range m.PathRoutes {
		id := fmt.Sprintf("%s_%s", fe, pr.Prefix)
		fmt.Fprintf(&b, "    acl %s path_reg ^/%s/%s(/.*)?$\n", id, regexp.QuoteMeta(pr.Prefix), portPattern(pr.MinPort, pr.MaxPort))
		aclNames = append(aclNames, id)
		if pr.Transport == store.PathTransportWS || pr.Transport == store.PathTransportHU {
			needUpgrade = true
		}
	}
	if needUpgrade {
		fmt.Fprintf(&b, "    acl %s_up req.hdr(Upgrade) -m found\n", fe)
		for _, pr := range m.PathRoutes {
			if pr.Transport == store.PathTransportWS || pr.Transport == store.PathTransportHU {
				fmt.Fprintf(&b, "    http-request deny deny_status 404 if %s_%s !%s_up\n", fe, pr.Prefix, fe)
			}
		}
	}
	orJoin := strings.Join(aclNames, " || ")
	fmt.Fprintf(&b, "    use_backend %s_dyn if %s\n", be, orJoin)
	// mapping without static targets: everything not matching a route is a 404
	if len(m.Targets) == 0 {
		neg := make([]string, len(aclNames))
		for i, a := range aclNames {
			neg[i] = "!" + a
		}
		fmt.Fprintf(&b, "    http-request deny deny_status 404 if %s\n", strings.Join(neg, " "))
	}
	return b.String()
}

// portPattern builds the port part of the path regex: an alternation when a
// narrow range is configured, otherwise any digits.
func portPattern(min, max int) string {
	if min <= 0 || max <= 0 || min > max || max-min > 16 {
		return "[0-9]+"
	}
	parts := make([]string, 0, max-min+1)
	for p := min; p <= max; p++ {
		parts = append(parts, strconv.Itoa(p))
	}
	return "(" + strings.Join(parts, "|") + ")"
}

// renderHADynBackend emits the dynamic backend used by path routes: the
// destination port is extracted from the request path per request and applied
// with set-dst-port before the single dynamic server line.
func renderHADynBackend(be string, m store.Mapping) string {
	host := "127.0.0.1"
	if len(m.Targets) > 0 && m.Targets[0].Host != "" {
		host = m.Targets[0].Host
	}
	var b strings.Builder
	fmt.Fprintf(&b, "backend %s_dyn\n    mode http\n    timeout tunnel 3600s\n", be)
	for _, pr := range m.PathRoutes {
		// the prefix is user input: QuoteMeta keeps it literal inside the
		// regex; the guard ACL must require the numeric port too, otherwise
		// a non-numeric path would leave txn.pgport as the raw path and
		// set-dst-port would apply garbage
		fmt.Fprintf(&b, "    http-request set-var(txn.pgport) path,regsub(^/%s/([0-9]+)(/.*)?$,\\1) if { path_reg ^/%s/%s(/.*)?$ }\n",
			regexp.QuoteMeta(pr.Prefix), regexp.QuoteMeta(pr.Prefix), portPattern(pr.MinPort, pr.MaxPort))
	}
	b.WriteString("    http-request set-dst-port var(txn.pgport)\n")
	fmt.Fprintf(&b, "    server dynamic %s:1\n\n", host)
	return b.String()
}

// renderHAAccessRules emits client-IP allow/deny rules. L7 uses http-request,
// L4 uses tcp-request connection. When an allow rule exists, a final deny/reject
// enforces whitelist behaviour (first-match-wins).
func renderHAAccessRules(m store.Mapping, tcpMode bool) string {
	if len(m.AccessRules) == 0 {
		return ""
	}
	var b strings.Builder
	allow, deny := "http-request allow", "http-request deny"
	if tcpMode {
		allow, deny = "tcp-request connection accept", "tcp-request connection reject"
	}
	hasAllowRule := false
	for _, r := range m.AccessRules {
		verb := deny
		if r.Action == "allow" {
			verb = allow
			hasAllowRule = true
		}
		fmt.Fprintf(&b, "    %s if { src %s }\n", verb, escapeHA(r.Value))
	}
	if hasAllowRule {
		fmt.Fprintf(&b, "    %s\n", deny)
	}
	return b.String()
}

func bindIP(ip string) string {
	if ip == "" || ip == "0.0.0.0" {
		return "*"
	}
	if ip == "::" {
		return "*"
	}
	// bracket IPv6 literals so the port split is unambiguous
	if strings.Contains(ip, ":") {
		return "[" + ip + "]"
	}
	return ip
}

func escapeHA(s string) string {
	return strings.NewReplacer(" ", "\\ ", "\n", "", "#", "\\#").Replace(s)
}

func (HAProxyEngine) Validate(staged map[string]string, p Paths) error {
	tmp, err := os.MkdirTemp("", "portguard-haproxy-*")
	if err != nil {
		return err
	}
	defer os.RemoveAll(tmp)
	cfg := filepath.Join(tmp, "haproxy.cfg")
	if err := os.WriteFile(cfg, []byte(staged["haproxy.cfg"]), 0o644); err != nil {
		return err
	}
	// certs referenced by generated config live in p.CertsDir; validation only checks syntax
	cmd := exec.Command(p.HAProxyBin, "-c", "-f", cfg)
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("haproxy validation failed: %s", strings.TrimSpace(string(out)))
	}
	return nil
}

func (HAProxyEngine) Reload(p Paths) error {
	// zero-downtime reload when running; fall back to (re)start for a cold service
	if err := exec.Command("systemctl", "reload", "haproxy").Run(); err == nil {
		return nil
	}
	if err := exec.Command("systemctl", "restart", "haproxy").Run(); err == nil {
		return nil
	}
	return fmt.Errorf("haproxy reload failed")
}

var _ Engine = HAProxyEngine{}
