package proxy

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"

	"portguard/internal/store"
)

// NginxEngine owns the full /etc/nginx/nginx.conf (dedicated install).
// HTTP(S) mappings render into portguard/http.conf (inside http{}),
// TCP/UDP mappings into portguard/stream.conf (inside stream{}).
type NginxEngine struct{}

func (NginxEngine) Name() string { return "nginx" }

func (NginxEngine) ActiveFiles(p Paths) []string {
	dir := posixJoin(posixDir(p.NginxConf), "portguard")
	return []string{p.NginxConf, dir + "/http.conf", dir + "/stream.conf", "/var/lib/portguard/decoy/index.html"}
}

// LivePath maps staged rel paths ("nginx.conf", "portguard/http.conf", ...) to live locations.
func (NginxEngine) LivePath(p Paths, rel string) string {
	switch rel {
	case "nginx.conf":
		return p.NginxConf
	case "decoy/index.html":
		return "/var/lib/portguard/decoy/index.html"
	}
	return posixJoin(posixDir(p.NginxConf), rel)
}

// StagedRel maps a live absolute path back to the staged rel path.
func (NginxEngine) StagedRel(p Paths, live string) (string, bool) {
	live = strings.ReplaceAll(live, "\\", "/")
	switch live {
	case p.NginxConf:
		return "nginx.conf", true
	case posixJoin(posixDir(p.NginxConf), "portguard/http.conf"):
		return "portguard/http.conf", true
	case posixJoin(posixDir(p.NginxConf), "portguard/stream.conf"):
		return "portguard/stream.conf", true
	case "/var/lib/portguard/decoy/index.html":
		return "decoy/index.html", true
	}
	return "", false
}

func (NginxEngine) Render(mappings []store.Mapping, certs map[int64]store.Cert, p Paths) (map[string]string, error) {
	var upstreams, httpBlocks, streamBlocks strings.Builder

	sorted := make([]store.Mapping, len(mappings))
	copy(sorted, mappings)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].ID < sorted[j].ID })

	for _, m := range sorted {
		if !m.Enabled || m.Engine != "nginx" {
			continue
		}
		switch m.Protocol {
		case "http", "https":
			upstreams.WriteString(renderHTTPUpstream(m))
			block, err := renderHTTPServer(m, p)
			if err != nil {
				return nil, err
			}
			httpBlocks.WriteString(block)
		case "tcp", "udp":
			block := renderStreamServer(m)
			streamBlocks.WriteString(block)
		}
	}

	confDir := posixJoin(posixDir(p.NginxConf), "portguard")
	main := `# Generated by PortGuard — do not edit manually.
user www-data;
worker_processes auto;
pid /run/nginx.pid;
error_log /var/log/nginx/error.log;
include /etc/nginx/modules-enabled/*.conf;

events {
    worker_connections 1024;
}

http {
    sendfile on;
    tcp_nopush on;
    types_hash_max_size 2048;
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;
    access_log /var/log/nginx/access.log;
    gzip on;
    client_max_body_size 0;

    include ` + confDir + `/http.conf;
}

stream {
    include ` + confDir + `/stream.conf;
}
`
	files := map[string]string{
		"nginx.conf":            main,
		"portguard/http.conf":   upstreams.String() + httpBlocks.String() + "# --- end of PortGuard http mappings ---\n",
		"portguard/stream.conf": streamBlocks.String() + "# --- end of PortGuard stream mappings ---\n",
	}
	for rel, content := range DecoyFiles(sorted) {
		files[rel] = content
	}
	return files, nil
}

func renderHTTPServer(m store.Mapping, p Paths) (string, error) {
	var b strings.Builder
	listen := nginxListenAddr(m.ListenIP, m.ListenPort)
	// a specific IP only listens on that family; the [::] companion line is
	// added only for wildcard listeners
	wildcard := m.ListenIP == "" || m.ListenIP == "0.0.0.0" || m.ListenIP == "::"
	fmt.Fprintf(&b, "    # mapping #%d: %s\n    server {\n", m.ID, escapeNginxComment(m.Name))

	if m.Protocol == "https" {
		if m.SSLCertID == nil {
			return "", fmt.Errorf("mapping #%d: https requires a certificate", m.ID)
		}
		certPath := fmt.Sprintf("%s/%d.crt", p.CertsDir, *m.SSLCertID)
		keyPath := fmt.Sprintf("%s/%d.key", p.CertsDir, *m.SSLCertID)
		h2 := ""
		if m.HTTP2 {
			h2 = " http2"
		}
		fmt.Fprintf(&b, "        listen %s ssl%s;\n", listen, h2)
		if wildcard {
			fmt.Fprintf(&b, "        listen [::]:%d ssl%s;\n", m.ListenPort, h2)
		}
		fmt.Fprintf(&b, "        ssl_certificate     %s;\n        ssl_certificate_key %s;\n", certPath, keyPath)
	} else {
		fmt.Fprintf(&b, "        listen %s;\n", listen)
		if wildcard {
			fmt.Fprintf(&b, "        listen [::]:%d;\n", m.ListenPort)
		}
	}

	if len(m.ServerNames) > 0 {
		names := make([]string, len(m.ServerNames))
		for i, sn := range m.ServerNames {
			names[i] = escapeNginx(sn)
		}
		fmt.Fprintf(&b, "        server_name %s;\n", strings.Join(names, " "))
	} else {
		b.WriteString("        server_name _;\n")
	}

	b.WriteString(renderNginxAccessRules(m))

	if m.RedirectTo != "" {
		fmt.Fprintf(&b, "        return 301 %s;\n", escapeNginx(m.RedirectTo))
	} else {
		// dynamic port-in-path routes (ws/httpupgrade/xhttp) take precedence
		// over the static proxy location blocks.
		b.WriteString(renderNginxPathRoutes(m))
		if m.PathPrefix != "" {
			// path-prefix routing: proxy only the prefix, reject everything else
			fmt.Fprintf(&b, "        location %s {\n", m.PathPrefix)
			b.WriteString(renderProxyHeaders(m))
			b.WriteString(renderWSHeaders(m))
			b.WriteString(renderProxyPass(m))
			b.WriteString("        }\n")
		} else if len(m.Targets) > 0 {
			// whole-site proxy
			b.WriteString("        location / {\n")
			b.WriteString(renderProxyHeaders(m))
			b.WriteString(renderWSHeaders(m))
			b.WriteString(renderProxyPass(m))
			b.WriteString("        }\n")
		}
		// unmatched paths: decoy site (anti-DPI) or 404
		b.WriteString(renderNginxFallback(m))
	}
	for k, v := range m.ExtraHeaders {
		fmt.Fprintf(&b, "        add_header %s \"%s\" always;\n", escapeNginx(k), escapeNginx(v))
	}
	b.WriteString("    }\n\n")
	return b.String(), nil
}

// renderProxyHeaders emits the standard proxy headers, honouring host_header.
func renderProxyHeaders(m store.Mapping) string {
	host := "$host"
	if m.HostHeader != "" {
		host = escapeNginx(m.HostHeader)
	}
	return fmt.Sprintf("            proxy_set_header Host %s;\n"+
		"            proxy_set_header X-Real-IP $remote_addr;\n"+
		"            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n"+
		"            proxy_set_header X-Forwarded-Proto $scheme;\n", host)
}

func renderWSHeaders(m store.Mapping) string {
	if !m.WebSocket {
		return ""
	}
	return "            proxy_http_version 1.1;\n" +
		"            proxy_set_header Upgrade $http_upgrade;\n" +
		"            proxy_set_header Connection \"upgrade\";\n" +
		"            proxy_read_timeout 3600s;\n"
}

func renderProxyPass(m store.Mapping) string {
	if len(m.Targets) == 1 {
		t := m.Targets[0]
		return fmt.Sprintf("            proxy_pass http://%s:%d;\n", escapeNginx(t.Host), t.Port)
	}
	return fmt.Sprintf("            proxy_pass http://pg_upstream_%d;\n", m.ID)
}

// renderNginxFallback decides what unmatched paths get: a real-looking decoy
// site (anti-DPI camouflage) or a plain 404. Only reachable when path routes or
// a path prefix guard the proxy locations above.
func renderNginxFallback(m store.Mapping) string {
	if m.Decoy == "" {
		if m.PathPrefix != "" || len(m.PathRoutes) > 0 || len(m.Targets) > 0 {
			if m.PathPrefix != "" || len(m.PathRoutes) > 0 {
				return "        location / {\n            return 404;\n        }\n"
			}
		}
		return ""
	}
	var b strings.Builder
	switch m.Decoy {
	case "builtin":
		b.WriteString("        location / {\n            root /var/lib/portguard/decoy;\n            index index.html;\n            try_files $uri $uri/ =404;\n        }\n")
	case "custom":
		b.WriteString("        location / {\n            root /var/lib/portguard/decoy;\n            index index.html;\n            try_files $uri $uri/ =404;\n        }\n")
	}
	return b.String()
}

// DecoyFiles returns the staged decoy webroot files for nginx mappings that
// request one (builtin templates or the user's custom HTML).
func DecoyFiles(mappings []store.Mapping) map[string]string {
	out := map[string]string{}
	for _, m := range mappings {
		if !m.Enabled || m.Engine != "nginx" || m.Decoy == "" || m.Protocol == "tcp" || m.Protocol == "udp" {
			continue
		}
		if _, ok := out["decoy/index.html"]; ok {
			continue // one shared webroot
		}
		switch m.Decoy {
		case "builtin":
			out["decoy/index.html"] = builtinDecoyHTML
		case "custom":
			out["decoy/index.html"] = m.DecoyHTML
		}
	}
	return out
}

const builtinDecoyHTML = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>CloudMetrics — Server Monitoring</title>
<style>
*{margin:0;padding:0;box-sizing:border-box}
body{font-family:system-ui,-apple-system,Segoe UI,Roboto,sans-serif;background:#f8fafc;color:#0f172a}
.nav{display:flex;justify-content:space-between;align-items:center;padding:1rem 2rem;background:#fff;border-bottom:1px solid #e2e8f0}
.brand{font-weight:700;font-size:1.1rem;color:#2563eb}
.hero{max-width:720px;margin:4rem auto;padding:0 1rem;text-align:center}
.hero h1{font-size:2.2rem;margin-bottom:1rem}
.hero p{color:#64748b;font-size:1.05rem;line-height:1.7;margin-bottom:2rem}
.cta{display:inline-block;background:#2563eb;color:#fff;padding:.75rem 1.5rem;border-radius:.5rem;text-decoration:none;font-weight:600}
.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:1rem;max-width:960px;margin:0 auto 4rem;padding:0 1rem}
.card{background:#fff;border:1px solid #e2e8f0;border-radius:.75rem;padding:1.5rem}
.card h3{font-size:1rem;margin-bottom:.5rem}
.card p{color:#64748b;font-size:.875rem;line-height:1.6}
footer{text-align:center;color:#94a3b8;font-size:.8rem;padding:2rem 0;border-top:1px solid #e2e8f0}
</style>
</head>
<body>
<nav class="nav"><span class="brand">CloudMetrics</span><span>Docs · Pricing · Sign in</span></nav>
<section class="hero">
<h1>Uptime and performance monitoring for modern teams</h1>
<p>Track latency, errors and traffic across your whole infrastructure from one
dashboard. Get alerted before your users notice. Free 14-day trial, no credit
card required.</p>
<a class="cta" href="#">Start monitoring</a>
</section>
<section class="grid">
<div class="card"><h3>Latency maps</h3><p>Global probe network with per-region percentiles and anomaly detection.</p></div>
<div class="card"><h3>Incident alerts</h3><p>Webhooks, email and Slack alerts the moment a check fails twice.</p></div>
<div class="card"><h3>SLA reports</h3><p>Beautiful monthly reports your customers will actually read.</p></div>
</section>
<footer>© 2026 CloudMetrics Inc. All rights reserved.</footer>
</body>
</html>
`

func renderHTTPUpstream(m store.Mapping) string {
	if m.RedirectTo != "" || len(m.Targets) <= 1 {
		return ""
	}
	var b strings.Builder
	fmt.Fprintf(&b, "    upstream pg_upstream_%d {\n", m.ID)
	switch m.Balance {
	case "least_conn":
		b.WriteString("        least_conn;\n")
	case "ip_hash":
		b.WriteString("        ip_hash;\n")
	case "random":
		b.WriteString("        random;\n")
	case "round_robin":
		// nginx default — no directive
		default:
			// legacy default: sticky for websockets, least connections otherwise
			if m.WebSocket {
				b.WriteString("        ip_hash;\n")
			} else {
				b.WriteString("        least_conn;\n")
			}
		}
	for _, t := range m.Targets {
		w := ""
		if t.Weight > 0 && t.Weight != 1 {
			w = fmt.Sprintf(" weight=%d", t.Weight)
		}
		bk := ""
		if t.Backup {
			bk = " backup"
		}
		fmt.Fprintf(&b, "        server %s:%d%s%s;\n", escapeNginx(t.Host), t.Port, w, bk)
	}
	b.WriteString("    }\n\n")
	return b.String()
}

func renderStreamServer(m store.Mapping) string {
	var b strings.Builder
	protoTag := ""
	if m.Protocol == "udp" {
		protoTag = " udp"
	}
	fmt.Fprintf(&b, "    # mapping #%d: %s\n    upstream pg_stream_%d {\n", m.ID, escapeNginxComment(m.Name), m.ID)
	switch m.Balance {
	case "least_conn":
		b.WriteString("        least_conn;\n")
	case "random":
		b.WriteString("        random;\n")
	}
	for _, t := range m.Targets {
		w := ""
		if t.Weight > 0 && t.Weight != 1 {
			w = fmt.Sprintf(" weight=%d", t.Weight)
		}
		fmt.Fprintf(&b, "        server %s:%d%s;\n", escapeNginx(t.Host), t.Port, w)
	}
	b.WriteString("    }\n")
	fmt.Fprintf(&b, "    server {\n        listen %s%s;\n        proxy_pass pg_stream_%d;\n        proxy_connect_timeout 5s;\n    }\n\n",
		nginxListenAddr(m.ListenIP, m.ListenPort), protoTag, m.ID)
	return b.String()
}

// renderNginxPathRoutes emits the dynamic port-in-path location blocks for
// ws / httpupgrade / xhttp transports (PasarGuard pattern: /<prefix>/<port>
// → 127.0.0.1:<port>). A single backend host can be set per mapping; without
// one, 127.0.0.1 is used (typical for local Xray inbounds).
func renderNginxPathRoutes(m store.Mapping) string {
	if len(m.PathRoutes) == 0 {
		return ""
	}
	host := pathRouteHost(m)
	var b strings.Builder
	for _, pr := range m.PathRoutes {
		fmt.Fprintf(&b, "        # %s transport -> /%s/<port>\n", pr.Transport, pr.Prefix)
		switch pr.Transport {
		case store.PathTransportWS, store.PathTransportHU:
			fmt.Fprintf(&b, "        location ~ ^/%s/(?<pgport>\\d+) {\n", escapeNginxRe(pr.Prefix))
			b.WriteString("            if ($http_upgrade = \"\") { return 404; }\n")
			fmt.Fprintf(&b, "            proxy_pass http://%s:$pgport;\n", escapeNginx(host))
			b.WriteString("            proxy_http_version 1.1;\n")
			b.WriteString("            proxy_set_header Upgrade $http_upgrade;\n")
			b.WriteString("            proxy_set_header Connection \"upgrade\";\n")
			b.WriteString("            proxy_set_header Host $host;\n")
			b.WriteString("            proxy_set_header X-Real-IP $remote_addr;\n")
			b.WriteString("            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n")
			b.WriteString("            proxy_read_timeout 1w;\n")
			b.WriteString("            proxy_send_timeout 1w;\n")
			b.WriteString("        }\n\n")
		case store.PathTransportXHTTP:
			fmt.Fprintf(&b, "        location ~ ^/%s/(?<pgport>\\d+)(/.*)? {\n", escapeNginxRe(pr.Prefix))
			fmt.Fprintf(&b, "            proxy_pass http://%s:$pgport;\n", escapeNginx(host))
			b.WriteString("            proxy_http_version 1.1;\n")
			b.WriteString("            proxy_set_header Host $host;\n")
			b.WriteString("            proxy_set_header X-Real-IP $remote_addr;\n")
			b.WriteString("            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n")
			b.WriteString("            proxy_set_header Connection \"\";\n")
			b.WriteString("            proxy_buffering off;\n")
			b.WriteString("            proxy_request_buffering off;\n")
			b.WriteString("            chunked_transfer_encoding on;\n")
			b.WriteString("            client_body_timeout 1w;\n")
			b.WriteString("            proxy_read_timeout 1w;\n")
			b.WriteString("            proxy_send_timeout 1w;\n")
			b.WriteString("        }\n\n")
		}
	}
	return b.String()
}

// pathRouteHost returns the backend host for dynamic path routes: the first
// regular target when present (relay setups), otherwise 127.0.0.1.
func pathRouteHost(m store.Mapping) string {
	if len(m.Targets) > 0 && m.Targets[0].Host != "" {
		return m.Targets[0].Host
	}
	return "127.0.0.1"
}

// escapeNginxRe escapes a literal token for use inside a nginx regex location.
func escapeNginxRe(s string) string {
	return strings.NewReplacer(" ", "\\ ").Replace(s)
}

// renderNginxAccessRules emits allow/deny directives (first-match-wins semantics).
// When an allow rule is present, a final "deny all" enforces whitelist behaviour.
func renderNginxAccessRules(m store.Mapping) string {
	if len(m.AccessRules) == 0 {
		return ""
	}
	var b strings.Builder
	hasAllow := false
	for _, r := range m.AccessRules {
		if r.Action == "allow" {
			hasAllow = true
		}
		fmt.Fprintf(&b, "        %s %s;\n", r.Action, escapeNginx(r.Value))
	}
	if hasAllow {
		b.WriteString("        deny all;\n")
	}
	return b.String()
}

// escapeNginx neutralises directive-breaking characters. Control characters
// and newlines are stripped entirely (validation rejects them anyway, but
// this is the render-time last line of defence against config injection).
func escapeNginx(s string) string {
	// strip control chars first, then escape the structural ones
	var b strings.Builder
	b.Grow(len(s))
	for _, r := range s {
		if r < 0x20 || r == 0x7f {
			continue
		}
		b.WriteRune(r)
	}
	return strings.NewReplacer(";", "\\;", "{", "\\{", "}", "\\}", "\"", "\\\"", "\\", "\\\\").Replace(b.String())
}

// escapeNginxComment makes arbitrary text safe inside a `# comment` line:
// newlines would end the comment and inject directives, so they are removed.
func escapeNginxComment(s string) string {
	var b strings.Builder
	b.Grow(len(s))
	for _, r := range s {
		if r == '\n' || r == '\r' || r < 0x20 || r == 0x7f {
			continue
		}
		b.WriteRune(r)
	}
	return b.String()
}

// nginxListenAddr renders a listen address:port for the given IP. IPv6
// literals are bracketed (except the bare "::" wildcard which becomes plain
// [::]).
func nginxListenAddr(ip string, port int) string {
	if ip == "::" || ip == "" {
		return fmt.Sprintf("[::]:%d", port)
	}
	if strings.Contains(ip, ":") { // IPv6 literal
		return fmt.Sprintf("[%s]:%d", ip, port)
	}
	return fmt.Sprintf("%s:%d", ip, port)
}

func (NginxEngine) Validate(staged map[string]string, p Paths) error {
	tmp, err := os.MkdirTemp("", "portguard-nginx-*")
	if err != nil {
		return err
	}
	defer os.RemoveAll(tmp)
	confDir := filepath.Join(tmp, "portguard")
	if err := os.MkdirAll(confDir, 0o755); err != nil {
		return err
	}
	main := strings.ReplaceAll(staged["nginx.conf"], posixJoin(posixDir(p.NginxConf), "portguard"), confDir)
	for rel, content := range staged {
		if rel == "nginx.conf" {
			continue
		}
		if rel == "decoy/index.html" {
			// nginx -t does not stat `root` directories; the decoy webroot is
			// written to its live location by the apply pipeline, skip it here
			continue
		}
		dst := filepath.Join(confDir, strings.TrimPrefix(rel, "portguard/"))
		if err := os.MkdirAll(filepath.Dir(dst), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(dst, []byte(content), 0o644); err != nil {
			return err
		}
	}
	mainPath := filepath.Join(tmp, "nginx.conf")
	if err := os.WriteFile(mainPath, []byte(main), 0o644); err != nil {
		return err
	}
	cmd := exec.Command(p.NginxBin, "-t", "-c", mainPath)
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("nginx validation failed: %s", strings.TrimSpace(string(out)))
	}
	return nil
}

func (NginxEngine) Reload(p Paths) error {
	// zero-downtime reload when running; fall back to (re)start for a cold service
	if err := exec.Command("systemctl", "reload", "nginx").Run(); err == nil {
		return nil
	}
	if err := exec.Command("systemctl", "restart", "nginx").Run(); err == nil {
		return nil
	}
	out, err := exec.Command(p.NginxBin, "-s", "reload").CombinedOutput()
	if err != nil {
		return fmt.Errorf("nginx reload failed: %s", strings.TrimSpace(string(out)))
	}
	return nil
}

var _ Engine = NginxEngine{}
