package proxy

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"

	"portguard/internal/store"
)

// NginxEngine owns the full /etc/nginx/nginx.conf (dedicated install).
// HTTP(S) mappings render into portguard/http.conf (inside http{}),
// TCP/UDP mappings into portguard/stream.conf (inside stream{}).
type NginxEngine struct{}

func (NginxEngine) Name() string { return "nginx" }

func (NginxEngine) ActiveFiles(p Paths) []string {
	dir := posixJoin(posixDir(p.NginxConf), "portguard")
	return []string{p.NginxConf, dir + "/http.conf", dir + "/stream.conf"}
}

// LivePath maps staged rel paths ("nginx.conf", "portguard/http.conf", ...) to live locations.
func (NginxEngine) LivePath(p Paths, rel string) string {
	if rel == "nginx.conf" {
		return p.NginxConf
	}
	return posixJoin(posixDir(p.NginxConf), rel)
}

// StagedRel maps a live absolute path back to the staged rel path.
func (NginxEngine) StagedRel(p Paths, live string) (string, bool) {
	live = strings.ReplaceAll(live, "\\", "/")
	switch live {
	case p.NginxConf:
		return "nginx.conf", true
	case posixJoin(posixDir(p.NginxConf), "portguard/http.conf"):
		return "portguard/http.conf", true
	case posixJoin(posixDir(p.NginxConf), "portguard/stream.conf"):
		return "portguard/stream.conf", true
	}
	return "", false
}

func (NginxEngine) Render(mappings []store.Mapping, certs map[int64]store.Cert, p Paths) (map[string]string, error) {
	var upstreams, httpBlocks, streamBlocks strings.Builder

	sorted := make([]store.Mapping, len(mappings))
	copy(sorted, mappings)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].ID < sorted[j].ID })

	for _, m := range sorted {
		if !m.Enabled || m.Engine != "nginx" {
			continue
		}
		switch m.Protocol {
		case "http", "https":
			upstreams.WriteString(renderHTTPUpstream(m))
			block, err := renderHTTPServer(m, p)
			if err != nil {
				return nil, err
			}
			httpBlocks.WriteString(block)
		case "tcp", "udp":
			block := renderStreamServer(m)
			streamBlocks.WriteString(block)
		}
	}

	confDir := posixJoin(posixDir(p.NginxConf), "portguard")
	main := `# Generated by PortGuard — do not edit manually.
user www-data;
worker_processes auto;
pid /run/nginx.pid;
error_log /var/log/nginx/error.log;
include /etc/nginx/modules-enabled/*.conf;

events {
    worker_connections 1024;
}

http {
    sendfile on;
    tcp_nopush on;
    types_hash_max_size 2048;
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers off;
    access_log /var/log/nginx/access.log;
    gzip on;
    client_max_body_size 0;

    include ` + confDir + `/http.conf;
}

stream {
    include ` + confDir + `/stream.conf;
}
`
	files := map[string]string{
		"nginx.conf":            main,
		"portguard/http.conf":   upstreams.String() + httpBlocks.String() + "# --- end of PortGuard http mappings ---\n",
		"portguard/stream.conf": streamBlocks.String() + "# --- end of PortGuard stream mappings ---\n",
	}
	return files, nil
}

func renderHTTPServer(m store.Mapping, p Paths) (string, error) {
	var b strings.Builder
	listen := m.ListenIP + ":" + itoa(m.ListenPort)
	fmt.Fprintf(&b, "    # mapping #%d: %s\n    server {\n", m.ID, m.Name)

	if m.Protocol == "https" {
		if m.SSLCertID == nil {
			return "", fmt.Errorf("mapping #%d: https requires a certificate", m.ID)
		}
		certPath := fmt.Sprintf("%s/%d.crt", p.CertsDir, *m.SSLCertID)
		keyPath := fmt.Sprintf("%s/%d.key", p.CertsDir, *m.SSLCertID)
		h2 := ""
		if m.HTTP2 {
			h2 = " http2"
		}
		fmt.Fprintf(&b, "        listen %s ssl%s;\n        listen [::]:%d ssl%s;\n", listen, h2, m.ListenPort, h2)
		fmt.Fprintf(&b, "        ssl_certificate     %s;\n        ssl_certificate_key %s;\n", certPath, keyPath)
	} else {
		fmt.Fprintf(&b, "        listen %s;\n        listen [::]:%d;\n", listen, m.ListenPort)
	}

	if len(m.ServerNames) > 0 {
		names := make([]string, len(m.ServerNames))
		for i, sn := range m.ServerNames {
			names[i] = escapeNginx(sn)
		}
		fmt.Fprintf(&b, "        server_name %s;\n", strings.Join(names, " "))
	} else {
		b.WriteString("        server_name _;\n")
	}

	b.WriteString(renderNginxAccessRules(m))

	if m.RedirectTo != "" {
		fmt.Fprintf(&b, "        return 301 %s;\n", escapeNginx(m.RedirectTo))
	} else {
		// dynamic port-in-path routes (ws/httpupgrade/xhttp) take precedence
		// over the static proxy location blocks.
		b.WriteString(renderNginxPathRoutes(m))
		// path-prefix routing: proxy only the prefix, reject everything else
		loc := "/"
		if m.PathPrefix != "" {
			loc = m.PathPrefix
		}
		fmt.Fprintf(&b, "        location %s {\n", loc)
		for _, h := range proxyHeaders() {
			fmt.Fprintf(&b, "            %s\n", h)
		}
		if m.WebSocket {
			b.WriteString("            proxy_http_version 1.1;\n")
			b.WriteString("            proxy_set_header Upgrade $http_upgrade;\n")
			b.WriteString("            proxy_set_header Connection \"upgrade\";\n")
			b.WriteString("            proxy_read_timeout 3600s;\n")
		}
		if len(m.Targets) == 1 {
			t := m.Targets[0]
			fmt.Fprintf(&b, "            proxy_pass http://%s:%d;\n", escapeNginx(t.Host), t.Port)
		} else {
			fmt.Fprintf(&b, "            proxy_pass http://pg_upstream_%d;\n", m.ID)
		}
		b.WriteString("        }\n")
		if m.PathPrefix != "" {
			b.WriteString("        location / {\n            return 404;\n        }\n")
		}
	}
	for k, v := range m.ExtraHeaders {
		fmt.Fprintf(&b, "        add_header %s \"%s\" always;\n", escapeNginx(k), escapeNginx(v))
	}
	b.WriteString("    }\n\n")
	return b.String(), nil
}

func renderHTTPUpstream(m store.Mapping) string {
	if m.RedirectTo != "" || len(m.Targets) <= 1 {
		return ""
	}
	var b strings.Builder
	fmt.Fprintf(&b, "    upstream pg_upstream_%d {\n", m.ID)
	switch m.Balance {
	case "least_conn":
		b.WriteString("        least_conn;\n")
	case "ip_hash":
		b.WriteString("        ip_hash;\n")
	case "random":
		b.WriteString("        random;\n")
	case "round_robin":
		// nginx default — no directive
		default:
			// legacy default: sticky for websockets, least connections otherwise
			if m.WebSocket {
				b.WriteString("        ip_hash;\n")
			} else {
				b.WriteString("        least_conn;\n")
			}
		}
	for _, t := range m.Targets {
		w := ""
		if t.Weight > 0 && t.Weight != 1 {
			w = fmt.Sprintf(" weight=%d", t.Weight)
		}
		bk := ""
		if t.Backup {
			bk = " backup"
		}
		fmt.Fprintf(&b, "        server %s:%d%s%s;\n", escapeNginx(t.Host), t.Port, w, bk)
	}
	b.WriteString("    }\n\n")
	return b.String()
}

func renderStreamServer(m store.Mapping) string {
	var b strings.Builder
	protoTag := ""
	if m.Protocol == "udp" {
		protoTag = " udp"
	}
	fmt.Fprintf(&b, "    # mapping #%d: %s\n    upstream pg_stream_%d {\n", m.ID, m.Name, m.ID)
	switch m.Balance {
	case "least_conn":
		b.WriteString("        least_conn;\n")
	case "random":
		b.WriteString("        random;\n")
	}
	for _, t := range m.Targets {
		w := ""
		if t.Weight > 0 && t.Weight != 1 {
			w = fmt.Sprintf(" weight=%d", t.Weight)
		}
		fmt.Fprintf(&b, "        server %s:%d%s;\n", escapeNginx(t.Host), t.Port, w)
	}
	b.WriteString("    }\n")
	fmt.Fprintf(&b, "    server {\n        listen %s:%d%s;\n        proxy_pass pg_stream_%d;\n        proxy_connect_timeout 5s;\n    }\n\n",
		m.ListenIP, m.ListenPort, protoTag, m.ID)
	return b.String()
}

// renderNginxPathRoutes emits the dynamic port-in-path location blocks for
// ws / httpupgrade / xhttp transports (PasarGuard pattern: /<prefix>/<port>
// → 127.0.0.1:<port>). A single backend host can be set per mapping; without
// one, 127.0.0.1 is used (typical for local Xray inbounds).
func renderNginxPathRoutes(m store.Mapping) string {
	if len(m.PathRoutes) == 0 {
		return ""
	}
	host := pathRouteHost(m)
	var b strings.Builder
	for _, pr := range m.PathRoutes {
		fmt.Fprintf(&b, "        # %s transport -> /%s/<port>\n", pr.Transport, pr.Prefix)
		switch pr.Transport {
		case store.PathTransportWS, store.PathTransportHU:
			fmt.Fprintf(&b, "        location ~ ^/%s/(?<pgport>\\d+) {\n", escapeNginxRe(pr.Prefix))
			b.WriteString("            if ($http_upgrade = \"\") { return 404; }\n")
			fmt.Fprintf(&b, "            proxy_pass http://%s:$pgport;\n", escapeNginx(host))
			b.WriteString("            proxy_http_version 1.1;\n")
			b.WriteString("            proxy_set_header Upgrade $http_upgrade;\n")
			b.WriteString("            proxy_set_header Connection \"upgrade\";\n")
			b.WriteString("            proxy_set_header Host $host;\n")
			b.WriteString("            proxy_set_header X-Real-IP $remote_addr;\n")
			b.WriteString("            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n")
			b.WriteString("            proxy_read_timeout 1w;\n")
			b.WriteString("            proxy_send_timeout 1w;\n")
			b.WriteString("        }\n\n")
		case store.PathTransportXHTTP:
			fmt.Fprintf(&b, "        location ~ ^/%s/(?<pgport>\\d+)(/.*)? {\n", escapeNginxRe(pr.Prefix))
			fmt.Fprintf(&b, "            proxy_pass http://%s:$pgport;\n", escapeNginx(host))
			b.WriteString("            proxy_http_version 1.1;\n")
			b.WriteString("            proxy_set_header Host $host;\n")
			b.WriteString("            proxy_set_header X-Real-IP $remote_addr;\n")
			b.WriteString("            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;\n")
			b.WriteString("            proxy_set_header Connection \"\";\n")
			b.WriteString("            proxy_buffering off;\n")
			b.WriteString("            proxy_request_buffering off;\n")
			b.WriteString("            chunked_transfer_encoding on;\n")
			b.WriteString("            client_body_timeout 1w;\n")
			b.WriteString("            proxy_read_timeout 1w;\n")
			b.WriteString("            proxy_send_timeout 1w;\n")
			b.WriteString("        }\n\n")
		}
	}
	return b.String()
}

// pathRouteHost returns the backend host for dynamic path routes: the first
// regular target when present (relay setups), otherwise 127.0.0.1.
func pathRouteHost(m store.Mapping) string {
	if len(m.Targets) > 0 && m.Targets[0].Host != "" {
		return m.Targets[0].Host
	}
	return "127.0.0.1"
}

// escapeNginxRe escapes a literal token for use inside a nginx regex location.
func escapeNginxRe(s string) string {
	return strings.NewReplacer(" ", "\\ ").Replace(s)
}

// renderNginxAccessRules emits allow/deny directives (first-match-wins semantics).
// When an allow rule is present, a final "deny all" enforces whitelist behaviour.
func renderNginxAccessRules(m store.Mapping) string {
	if len(m.AccessRules) == 0 {
		return ""
	}
	var b strings.Builder
	hasAllow := false
	for _, r := range m.AccessRules {
		if r.Action == "allow" {
			hasAllow = true
		}
		fmt.Fprintf(&b, "        %s %s;\n", r.Action, escapeNginx(r.Value))
	}
	if hasAllow {
		b.WriteString("        deny all;\n")
	}
	return b.String()
}

func proxyHeaders() []string {
	return []string{
		"proxy_set_header Host $host;",
		"proxy_set_header X-Real-IP $remote_addr;",
		"proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;",
		"proxy_set_header X-Forwarded-Proto $scheme;",
	}
}

func escapeNginx(s string) string {
	return strings.NewReplacer(";", "\\;", "{", "\\{", "}", "\\}", "\"", "\\\"", "\\", "\\\\").Replace(s)
}

func itoa(n int) string { return fmt.Sprintf("%d", n) }

func (NginxEngine) Validate(staged map[string]string, p Paths) error {
	tmp, err := os.MkdirTemp("", "portguard-nginx-*")
	if err != nil {
		return err
	}
	defer os.RemoveAll(tmp)
	confDir := filepath.Join(tmp, "portguard")
	if err := os.MkdirAll(confDir, 0o755); err != nil {
		return err
	}
	main := strings.ReplaceAll(staged["nginx.conf"], posixJoin(posixDir(p.NginxConf), "portguard"), confDir)
	for rel, content := range staged {
		if rel == "nginx.conf" {
			continue
		}
		dst := filepath.Join(confDir, strings.TrimPrefix(rel, "portguard/"))
		if err := os.MkdirAll(filepath.Dir(dst), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(dst, []byte(content), 0o644); err != nil {
			return err
		}
	}
	mainPath := filepath.Join(tmp, "nginx.conf")
	if err := os.WriteFile(mainPath, []byte(main), 0o644); err != nil {
		return err
	}
	cmd := exec.Command(p.NginxBin, "-t", "-c", mainPath)
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("nginx validation failed: %s", strings.TrimSpace(string(out)))
	}
	return nil
}

func (NginxEngine) Reload(p Paths) error {
	// zero-downtime reload when running; fall back to (re)start for a cold service
	if err := exec.Command("systemctl", "reload", "nginx").Run(); err == nil {
		return nil
	}
	if err := exec.Command("systemctl", "restart", "nginx").Run(); err == nil {
		return nil
	}
	out, err := exec.Command(p.NginxBin, "-s", "reload").CombinedOutput()
	if err != nil {
		return fmt.Errorf("nginx reload failed: %s", strings.TrimSpace(string(out)))
	}
	return nil
}

var _ Engine = NginxEngine{}
